/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollsIndexRouteImport } from './routes/polls.index'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as PollsSlugRouteImport } from './routes/polls.$slug'
import { Route as ApiFirecrawlDetailsRouteImport } from './routes/api.firecrawl-details'
import { Route as ApiFirecrawlBackfillRouteImport } from './routes/api.firecrawl-backfill'
import { Route as AdminPollsRouteImport } from './routes/admin.polls'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIndexRoute = PollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsSlugRoute = PollsSlugRouteImport.update({
  id: '/polls/$slug',
  path: '/polls/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlDetailsRoute = ApiFirecrawlDetailsRouteImport.update({
  id: '/api/firecrawl-details',
  path: '/api/firecrawl-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirecrawlBackfillRoute = ApiFirecrawlBackfillRouteImport.update({
  id: '/api/firecrawl-backfill',
  path: '/api/firecrawl-backfill',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPollsRoute = AdminPollsRouteImport.update({
  id: '/admin/polls',
  path: '/admin/polls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/polls': typeof AdminPollsRoute
  '/api/firecrawl-backfill': typeof ApiFirecrawlBackfillRoute
  '/api/firecrawl-details': typeof ApiFirecrawlDetailsRoute
  '/polls/$slug': typeof PollsSlugRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/polls/': typeof PollsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/polls': typeof AdminPollsRoute
  '/api/firecrawl-backfill': typeof ApiFirecrawlBackfillRoute
  '/api/firecrawl-details': typeof ApiFirecrawlDetailsRoute
  '/polls/$slug': typeof PollsSlugRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/polls': typeof PollsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/polls': typeof AdminPollsRoute
  '/api/firecrawl-backfill': typeof ApiFirecrawlBackfillRoute
  '/api/firecrawl-details': typeof ApiFirecrawlDetailsRoute
  '/polls/$slug': typeof PollsSlugRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/polls/': typeof PollsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/polls'
    | '/api/firecrawl-backfill'
    | '/api/firecrawl-details'
    | '/polls/$slug'
    | '/restaurant/$id'
    | '/polls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/polls'
    | '/api/firecrawl-backfill'
    | '/api/firecrawl-details'
    | '/polls/$slug'
    | '/restaurant/$id'
    | '/polls'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/polls'
    | '/api/firecrawl-backfill'
    | '/api/firecrawl-details'
    | '/polls/$slug'
    | '/restaurant/$id'
    | '/polls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminPollsRoute: typeof AdminPollsRoute
  ApiFirecrawlBackfillRoute: typeof ApiFirecrawlBackfillRoute
  ApiFirecrawlDetailsRoute: typeof ApiFirecrawlDetailsRoute
  PollsSlugRoute: typeof PollsSlugRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  PollsIndexRoute: typeof PollsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/': {
      id: '/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof PollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$slug': {
      id: '/polls/$slug'
      path: '/polls/$slug'
      fullPath: '/polls/$slug'
      preLoaderRoute: typeof PollsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl-details': {
      id: '/api/firecrawl-details'
      path: '/api/firecrawl-details'
      fullPath: '/api/firecrawl-details'
      preLoaderRoute: typeof ApiFirecrawlDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firecrawl-backfill': {
      id: '/api/firecrawl-backfill'
      path: '/api/firecrawl-backfill'
      fullPath: '/api/firecrawl-backfill'
      preLoaderRoute: typeof ApiFirecrawlBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polls': {
      id: '/admin/polls'
      path: '/admin/polls'
      fullPath: '/admin/polls'
      preLoaderRoute: typeof AdminPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminPollsRoute: AdminPollsRoute,
  ApiFirecrawlBackfillRoute: ApiFirecrawlBackfillRoute,
  ApiFirecrawlDetailsRoute: ApiFirecrawlDetailsRoute,
  PollsSlugRoute: PollsSlugRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  PollsIndexRoute: PollsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
